### ISSUE TITLE
Caused by: java.lang.IllegalStateException: bag-of-cells error: reference #0 of cell #0 is to non-existent cell #10312, only 1172 cells are defined

### ISSUE THREAD

**Issue by andreypfau** [andreypfau/ton-kotlin#22]
```
Exception in thread "main" java.lang.IllegalArgumentException: Can't load BoC: https://gist.github.com/andreypfau/10263901d0bd943a6f012a487855da50
	at org.ton.boc.BagOfCells$Companion.of(BagOfCells.kt:39)
	at org.ton.boc.BagOfCellsKt.BagOfCells(BagOfCells.kt:7)
	at org.ton.lite.api.liteserver.LiteServerBlockData.dataBagOfCells(LiteServerBlockData.kt:21)
	at org.ton.lite.api.liteserver.LiteServerBlockData.toBlock(LiteServerBlockData.kt:23)
	at TestKt.transactionsRealtime(test.kt:58)
	at TestKt$transactionsRealtime$1.invokeSuspend(test.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)
	at org.ton.adnl.AdnlTcpClient$sendQuery$2$1.invokeSuspend(AdnlTcpClient.kt:72)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: bag-of-cells error: reference #0 of cell #0 is to non-existent cell #10312, only 1172 cells are defined
	at org.ton.boc.BagOfCellsUtilsKt.readBagOfCell(BagOfCellsUtils.kt:110)
	at org.ton.boc.BagOfCells$Companion.of(BagOfCells.kt:37)
	... 14 more
	```

**Comment by andreypfau** [comment]
Fixed in new versions. Here deserialized result:
https://gist.github.com/andreypfau/09bd0c23d77910838493ed8d307dc13e
