### ISSUE TITLE
Can't parse block: (-1:8000000000000000:24533340)

### ISSUE THREAD

**Issue by 90K2** [andreypfau/ton-kotlin#53]
Setup:

```
@Test
    fun `load block`() {
        val lite = LiteClient(
            LiteClientConfigGlobal(
                liteservers = listOf(
                    LiteServerDesc(id = PublicKeyEd25519(base64("aF91CuUHuuOv9rm2W5+O/4h38M3sRm40DtSdRxQhmtQ=")), ip = -2018135749, port = 53312)
                ),
                validator = ValidatorConfigGlobal()
            )
        )

        val blockId = 24533340
        runBlocking {
            lite.lookupBlock(
                TonNodeBlockId(workchain = -1, shard = Long.MIN_VALUE, seqno = blockId)
            )?.let {
                println(lite.getBlock(it))
            }
        }
    }
```

stacktrace:

```
Can't parse block: (-1:8000000000000000:24533340):44B2F2B204734A082282E63A9C2CFB46C16AE5497E588FAF0634131B2E98F374:F221C4081B538D6C1C6C9C8803BE2FA8C6E2F90FC99983FF5A9E2562B80686A3
java.lang.RuntimeException: Can't parse block: (-1:8000000000000000:24533340):44B2F2B204734A082282E63A9C2CFB46C16AE5497E588FAF0634131B2E98F374:F221C4081B538D6C1C6C9C8803BE2FA8C6E2F90FC99983FF5A9E2562B80686A3
	at org.ton.lite.client.LiteClient.getBlock(LiteClient.kt:293)
	at org.ton.lite.client.LiteClient$getBlock$3.invokeSuspend(LiteClient.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.project.TonModuleTest.load block(TonModuleTest.kt:253)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at kotlin.collections.EmptyList.get(Collections.kt:36)
	at kotlin.collections.EmptyList.get(Collections.kt:24)
	at org.ton.cell.CellSliceImpl.preloadRef(CellSlice.kt:104)
	at org.ton.cell.CellSliceImpl.loadRef(CellSlice.kt:97)
	at org.ton.hashmap.HashMapNodeTlbCombinator$HashMapNodeForkTlbConstructor.loadTlb(HashMapNode.kt:124)
	at org.ton.hashmap.HashMapNodeTlbCombinator.loadTlb(HashMapNode.kt:43)
	at org.ton.hashmap.HashMapNodeTlbCombinator.loadTlb(HashMapNode.kt:21)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.loadTlb(HashMapEdge.kt:79)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.loadTlb(HashMapEdge.kt:46)
	at org.ton.hashmap.HashMapNodeTlbCombinator$HashMapNodeForkTlbConstructor.loadTlb(HashMapNode.kt:125)
	at org.ton.hashmap.HashMapNodeTlbCombinator.loadTlb(HashMapNode.kt:43)
	at org.ton.hashmap.HashMapNodeTlbCombinator.loadTlb(HashMapNode.kt:21)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.loadTlb(HashMapEdge.kt:79)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.loadTlb(HashMapEdge.kt:46)
	at org.ton.hashmap.HashMapNodeTlbCombinator$HashMapNodeForkTlbConstructor.loadTlb(HashMapNode.kt:125)
	at org.ton.hashmap.HashMapNodeTlbCombinator.loadTlb(HashMapNode.kt:43)
	at org.ton.hashmap.HashMapNodeTlbCombinator.loadTlb(HashMapNode.kt:21)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.loadTlb(HashMapEdge.kt:79)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.loadTlb(HashMapEdge.kt:46)
	at org.ton.hashmap.HashMapNodeTlbCombinator$HashMapNodeForkTlbConstructor.loadTlb(HashMapNode.kt:125)
	at org.ton.hashmap.HashMapNodeTlbCombinator.loadTlb(HashMapNode.kt:43)
	at org.ton.hashmap.HashMapNodeTlbCombinator.loadTlb(HashMapNode.kt:21)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.loadTlb(HashMapEdge.kt:79)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.loadTlb(HashMapEdge.kt:46)
	at org.ton.block.ConfigParamsTlbConstructor.loadTlb(ConfigParams.kt:60)
	at org.ton.block.ConfigParams$Companion.loadTlb(ConfigParams.kt)
	at org.ton.block.ConfigParams$Companion.loadTlb(ConfigParams.kt:22)
	at org.ton.block.McBlockExtraTlbConstructor.loadTlb(McBlockExtra.kt:108)
	at org.ton.block.McBlockExtraTlbConstructor.loadTlb(McBlockExtra.kt:28)
	at org.ton.tlb.TlbCombinator.loadTlb(TlbCombinator.kt:34)
	at org.ton.block.McBlockExtra$Companion.loadTlb(McBlockExtra.kt)
	at org.ton.block.McBlockExtra$Companion.loadTlb(McBlockExtra.kt:25)
	at org.ton.tlb.constructor.CellReferencedTlbConstructor.loadTlb(CellTlbConstructor.kt:63)
	at org.ton.block.MaybeTlbCombinator$JustConstructor.loadTlb(Maybe.kt:117)
	at org.ton.block.MaybeTlbCombinator$JustConstructor.loadTlb(Maybe.kt:84)
	at org.ton.tlb.TlbCombinator.loadTlb(TlbCombinator.kt:34)
	at org.ton.block.BlockExtraTlbConstructor.loadTlb(BlockExtra.kt:113)
	at org.ton.block.BlockExtraTlbConstructor.loadTlb(BlockExtra.kt:32)
	at org.ton.tlb.TlbCombinator.loadTlb(TlbCombinator.kt:34)
	at org.ton.block.BlockExtra$Companion.loadTlb(BlockExtra.kt)
	at org.ton.block.BlockExtra$Companion.loadTlb(BlockExtra.kt:29)
	at org.ton.block.Block$TlbConstructor.loadTlb(Block.kt:104)
	at org.ton.block.Block$TlbConstructor.loadTlb(Block.kt:26)
	at org.ton.tlb.TlbCombinator.loadTlb(TlbCombinator.kt:34)
	at org.ton.lite.client.LiteClient$getBlock$$inlined$parse$1.invoke(TlbCodec.kt:53)
	at org.ton.lite.client.LiteClient$getBlock$$inlined$parse$1.invoke(TlbCodec.kt:34)
	at org.ton.cell.Cell$DefaultImpls.parse(Cell.kt:56)
	at org.ton.cell.CellImpl.parse(CellImpl.kt:12)
	at org.ton.lite.client.LiteClient.getBlock(LiteClient.kt:536)
	... 95 more
```

upd. same for 24702356 for example

**Comment by 90K2** [comment]
version 0.2.14 OK
