### ISSUE TITLE
[0.2.6] Can't get Block's stateUpdate

### ISSUE THREAD

**Issue by AntonMeep** [andreypfau/ton-kotlin#70]
```kotlin
import io.ktor.util.*
import kotlinx.coroutines.CoroutineName
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import org.ton.api.liteserver.LiteServerDesc
import org.ton.api.pub.PublicKeyEd25519
import org.ton.lite.client.LiteClient

runBlocking {
    val liteClient = LiteClient(
        Dispatchers.IO + CoroutineName("liteClient"),
        LiteServerDesc(
            ip = 1091931625,
            port = 30131,
            id =  PublicKeyEd25519("wrQaeIFispPfHndEBc0s0fx7GSp8UFFvebnytQQfc6A=".decodeBase64Bytes())
        )
    )

    val id = liteClient.getLastBlockId()
    val block = liteClient.getBlock(id)
    block?.stateUpdate?.oldHash
}
```

Results in
```
Exception in thread "main" java.lang.IllegalStateException: bitsPosition: 512 != bits.length: 552
	at org.ton.cell.CellSliceImpl.endParse(CellSlice.kt:96)
	at org.ton.cell.Cell$DefaultImpls.parse(Cell.kt:62)
	at org.ton.cell.CellImpl.parse(CellImpl.kt:13)
	at org.ton.tlb.CellRefImpl$value$2.invoke(CellRef.kt:37)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at org.ton.tlb.CellRefImpl.getValue(CellRef.kt:36)
	at org.ton.tlb.CellRef$DefaultImpls.getValue(CellRef.kt:18)
	at org.ton.tlb.CellRefImpl.getValue(CellRef.kt:32)
	at org.ton.block.Block.getStateUpdate(Block.kt:20)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated$ScratchFileRunnerGenerated$generated_get_instance_res0$1$1.invokeSuspend(tmp.kt:26)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated$ScratchFileRunnerGenerated.generated_get_instance_res0(tmp.kt:14)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated.main(tmp.kt:33)

```

**Comment by andreypfau** [comment]
fixed in 0.2.7
