### ISSUE TITLE
IndexOutOfBoundsException when iterating AugDictionaryRoot

### ISSUE THREAD

**Issue by Tetraquark** [andreypfau/ton-kotlin#74]
Trying to get the last transaction hash value from `LiteServerAccountState` `proof` field. And get the exception `java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.` while iterating `AugDictionary`. Code example:

```kotlin
suspend fun printLastLtHash(address: String = "EQBnRcXDUmnXeAtPcsmGUQRhpvAyca4H0tHJ7edkj_pxNgBB") {
    val liteClient = LiteClient(
        coroutineContext = currentCoroutineContext(),
        LiteServerDesc(
            id = PublicKeyEd25519(base64("n4VDnSCUuSpjnCyUk9e3QOOd6o0ItSWYbTnW3Wnn8wk=")),
            ip = 84478511,
            port = 19949
        )
    )
    val accountId = LiteServerAccountId(AddrStd(address))

    val lastBlock = liteClient.getLastBlockId()
    val accountState = liteClient.liteApi(
        LiteServerGetAccountState(
            id = lastBlock,
            account = accountId
        )
    )

    BagOfCells(accountState.proof).first().beginParse().run {
        val slice = loadRef().beginParse()
        val shardState = slice.loadTlb(ShardState)

        when (shardState) {
            is SplitState -> TODO()
            is ShardStateUnsplit -> {
                val dictionaryRoot = shardState.accounts.value.x as AugDictionaryRoot<ShardAccount, DepthBalanceInfo>

                // Here we will get "java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0."
                // at loading some AugDictionaryNodeFork
                dictionaryRoot.root.value.nodes().forEach(::println)
            }
        }
    }
}
```

Part of the stacktrace:

```
java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at kotlin.collections.EmptyList.get(Collections.kt:36)
	at kotlin.collections.EmptyList.get(Collections.kt:24)
	at org.ton.cell.CellSliceImpl.preloadRef(CellSlice.kt:110)
	at org.ton.cell.CellSliceImpl.loadRef(CellSlice.kt:103)
	at org.ton.hashmap.AugDictionaryNodeForkTlbConstructor.loadTlb(AugDictionaryNodeFork.kt:80)
	at org.ton.hashmap.AugDictionaryNodeForkTlbConstructor.loadTlb(AugDictionaryNodeFork.kt:40)
	at org.ton.hashmap.AugDictionaryEdgeTlbConstructor.loadTlb(AugDictionaryEdge.kt:81)
	at org.ton.hashmap.AugDictionaryEdgeTlbConstructor.loadTlb(AugDictionaryEdge.kt:42)
        ...
```

Is this a TLB parsing problem or is the sample code just incorrect?

The goal is to get `ShardAccount` in the middle of the dictionary with cell:
```
value:(account_descr
  account:(!pruned_branch cell:x{0101CEFC031D0FDB88C6D2146567C...}) last_trans_hash:48E0F3D18A857233C3BB07D... last_trans_lt:350803850...)))
```

Library version: 0.2.14

**Comment by andreypfau** [comment]
Fixed in 0.2.15

Use get method from AugmentedDictionary for search value by key:
```kotlin
val dictionaryRoot = shardState.accounts.value.x
val value = dictionaryRoot[address]
```
