### ISSUE TITLE
IllegalArgumentException when send LiteServerGetTransactions request

### ISSUE THREAD

**Issue by Tetraquark** [andreypfau/ton-kotlin#77]
Get `IllegalArgumentException` at `TlConstructor.decodeBoxed(TlConstructor.kt:28)` when I try to send `LiteServerGetTransactions` request using `LiteApi`.

Stack trase:

```
java.lang.IllegalArgumentException: Invalid ID. expected: 9dd72eb9 (-1188112483) actual: 0bc6266f (1864812043)
	at org.ton.tl.TlConstructor.decodeBoxed(TlConstructor.kt:28)
	at org.ton.tl.TlDecoder$DefaultImpls.decodeBoxed(TlDecoder.kt:11)
	at org.ton.tl.TlCodec$DefaultImpls.decodeBoxed(TlCodec.kt:5)
	at org.ton.tl.TlConstructor.decodeBoxed(TlConstructor.kt:7)
	at org.ton.lite.api.liteserver.LiteServerTransactionList$Companion.decodeBoxed(LiteServerTransactionList.kt)
	at org.ton.lite.api.liteserver.LiteServerTransactionList$Companion.decodeBoxed(LiteServerTransactionList.kt:30)
	at org.ton.lite.api.LiteApiClient$DefaultImpls.sendQuery(LiteApiClient.kt:37)
```

Reproducer:

```kotlin
suspend fun transactionList(address: String = "EQBJpDx2dFtSAkHr8AMB4by3KeON_5GA0fC_rBYkWljFLqbg") {
    val liteClient = LiteClient(
        coroutineContext = currentCoroutineContext(),
        LiteServerDesc(
            id = PublicKeyEd25519(base64("n4VDnSCUuSpjnCyUk9e3QOOd6o0ItSWYbTnW3Wnn8wk=")),
            ip = 84478511,
            port = 19949
        )
    )
    val accountId = LiteServerAccountId(AddrStd(address))

    // Hardcoded data from the SharedAccount
    val lastTrLt = 35163722000006L
    val lastTrHash = BitString("4D40CB31E89AB79AC54A6ED840EEDC586E876034F548CDC39E99C0DA18E2475B").toByteArray()

    // throws IllegalArgumentException
    val transactionList = liteClient.liteApi(
        LiteServerGetTransactions(
            count = 1,
            account = accountId,
            lt = lastTrLt,
            hash = lastTrHash
        )
    )
}
```

**Comment by andreypfau** [comment]
fixed in 0.2.15
