### ISSUE TITLE
HashMapE.fromMap conversion error

### ISSUE THREAD

**Issue by 90K2** [andreypfau/ton-kotlin#78]
Sample:

```
    @Test
    fun hmapTest() {
        val targets = listOf(
                AddrStd("kQC7ryRspjsMrdnuuA98uGyLMUVd_dDWjroYLBHoIz9ovl7e")
        )
        val transfers = targets.map {
            WalletTransfer {
                destination = it
                coins = Coins.of(1)
                bounceable = true
                body = null
                stateInit = null
            }
        }
        val transfersBody = transfers.mapIndexed { index, walletTransfer ->
            BitString(index) to CellBuilder.createCell {
                storeUInt(walletTransfer.sendMode, 8)
                storeRef(MessageRelaxed.tlbCodec(AnyTlbConstructor), CellRef(AbstractWallet.createIntMsg(walletTransfer)))
            }
        }.toMap()

        CellBuilder.createCell {
            storeTlb(HashMapE.tlbCodec(16, Cell.tlbCodec()), HashMapE.fromMap(transfersBody))
        }
    }
```

StackTrace

```
class org.ton.hashmap.HmnLeaf cannot be cast to class org.ton.hashmap.HmnFork (org.ton.hashmap.HmnLeaf and org.ton.hashmap.HmnFork are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.ton.hashmap.HmnLeaf cannot be cast to class org.ton.hashmap.HmnFork (org.ton.hashmap.HmnLeaf and org.ton.hashmap.HmnFork are in unnamed module of loader 'app')
	at org.ton.hashmap.HashMapNodeForkTlbConstructor.storeTlb(HmnFork.kt:52)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.storeTlb(HmEdge.kt:122)
	at org.ton.hashmap.HashMapEdgeTlbConstructor.storeTlb(HmEdge.kt:92)
	at org.ton.tlb.CellRefValue$toCell$2.invoke(CellRef.kt:76)
	at org.ton.tlb.CellRefValue$toCell$2.invoke(CellRef.kt:75)
	at org.ton.cell.CellBuilder$Companion.createCell(CellBuilder.kt:97)
	at org.ton.tlb.CellRefValue.toCell(CellRef.kt:75)
	at org.ton.tlb.CellRefTlbConstructor.storeTlb(CellRef.kt:87)
	at org.ton.tlb.CellRefTlbConstructor.storeTlb(CellRef.kt:83)
	at org.ton.hashmap.RootHashMapETlbConstructor.storeTlb(HmeRoot.kt:73)
	at org.ton.hashmap.RootHashMapETlbConstructor.storeTlb(HmeRoot.kt:44)
	at org.ton.tlb.TlbCombinator.storeTlb(TlbCombinator.kt:59)
```

**Comment by andreypfau** [comment]
What is AbstractWallet?
Please provide complete example with imports

**Comment by 90K2** [comment]
updated
